### ISSUE TITLE
Access White List by user id

### ISSUE THREAD

**Issue by alfiankan** [alfiankan/teleterm#15]
according to https://github.com/alfiankan/teleterm/issues/14 Literally everybody can access the server through the bot and all bots are public with an @. In terms of functinality the bot is great but you need to add a Whitlist for users

white listing using telegram username on config file.
teleterm running using file `config.yaml` at /home-path/.teleterm/config.yaml. on this feature request the config file will be :

```yaml

teleterm:
  telegram_token: "xxxxxxxxx"
  shell_executor: "/bin/bash"
  whitelists:
    - sabrina
    - hilda
    - ambross
    - zelda

```

so only listed users on config file can execute command.

**Comment by alfajrimutawadhi** [comment]
assign to me, i'll try to solve this issue

**Comment by catty-dev** [comment]
It would be better to use the user id for whitelist and not username since the user id of your account will never changed. Also some people don't have an unsername

**Comment by alfajrimutawadhi** [comment]
that's right, thanks for your opinion

**Comment by alfiankan** [comment]
> It would be better to use the user id for whitelist and not username since the user id of your account will never changed. Also some people don't have an unsername

is it possible to get userid without using @userinfobot bot ? you're right about username, but what do you think if we use both username and user id as whitelist ? since username is easily accessible i think, but we still provide possibility to use user id as whitelist 

@alfajrimutawadhi @catty-dev 

```yaml

teleterm:
  telegram_token: "xxxxxxxxx"
  shell_executor: "/bin/bash"
  whitelists:
    - @sabrina
    - @hilda
    - @ambross
    - @zelda
    - 783277716
    - 133475712
```
